build:
	docker build -t tmather99/python-tcp-udp-server .

run:
	docker run -it --rm --name tcp-udp-python -p 54321:54321/tcp -p 12345:12345/udp -p 5000:5000/tcp -p 8484:8484/tcp tmather99/python-tcp-udp-server

push:
	docker push tmather99/python-tcp-udp-server

