build:
	docker build -t tmather99/python-tcp-server .

run:
	docker run -it --rm --name python-tcp-server -p 5000:5000/tcp -p 8484:8484/tcp tmather99/python-tcp-server

push:
	docker push tmather99/python-tcp-server

